letter_one:
  - enable: false
    x: 0
    y: 117
  - enable: true
    x: 354
    y: 117
  - enable: true
    x: 282
    y: 117
  - enable: true
    x: 229
    y: 117
  - enable: true
    x: 172
    y: 117
  - enable: true
    x: 115
    y: 117
  - enable: true
    x: 48
    y: 117
  - enable: false
    x: 0
    y: 117
  - enable: false
    x: 0
    y: 117
  - enable: false
    x: 0
    y: 117
letter_two:
  - enable: false
    x: 0
    y: 117
  - enable: false
    x: 0
    y: 117
  - enable: true
    x: 379
    y: 117
  - enable: true
    x: 331
    y: 117
  - enable: true
    x: 274
    y: 117
  - enable: true
    x: 217
    y: 117
  - enable: true
    x: 150
    y: 117
  - enable: true
    x: 92
    y: 117
  - enable: true
    x: 0
    y: 117
  - enable: false
    x: 0
    y: 117
letter_three:
  - enable: false
    x: 0
    y: 117
  - enable: false
    x: 0
    y: 117
  - enable: false
    x: 0
    y: 117
  - enable: false
    x: 0
    y: 117
  - enable: true
    x: 374
    y: 117
  - enable: true
    x: 317
    y: 117
  - enable: true
    x: 250
    y: 117
  - enable: true
    x: 192
    y: 117
  - enable: true
    x: 101
    y: 117
  - enable: false
    x: 0
    y: 117

